behavior_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0

    # Drone-appropriate behaviors
    behavior_plugins: ["spin", "wait"]

    spin:
      plugin: "nav2_behaviors/Spin"

    wait:
      plugin: "nav2_behaviors/Wait"

    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0

    # Drone yaw dynamics
    max_rotational_vel: 2.5
    min_rotational_vel: 0.2
    rotational_acc_lim: 5.0

    # Path to your Behavior Tree XML file
    # bt_xml_filename: "/media/mikelap/DATA21/Development/GithubRepos/robotics-sim-projects/uav_project_ws/src/uav_navigation/bt/bt_navigation_w_recalc.xml"
