bt_navigator:
  ros__parameters: 
    use_sim_time: true
    global_frame: map
    robot_base_frame: x650_0/base_footprint
    odom_topic: /x650_0/odom
    bt_loop_duration: 10
    default_server_timeout: 1000 # 1 sec
    enable_groot_monitoring: true
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    
    # Default behavior trees
    default_nav_to_pose_bt_xml: "/media/mikelap/DATA21/Development/GithubRepos/robotics-sim-projects/uav_project_ws/src/uav_navigation/bt/bt_navigation_w_recalc.xml"
    default_nav_through_poses_bt_xml: "/media/mikelap/DATA21/Development/GithubRepos/robotics-sim-projects/uav_project_ws/src/uav_navigation/bt/bt_navigation_w_recalc.xml"
    
    # Plugin library names
    plugin_lib_names: 
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_rate_controller_bt_node
    - nav2_pipeline_sequence_bt_node