bt_navigator:
  ros__parameters: 
    use_sim_time: true
    global_frame: map
    robot_base_frame: x650_0/base_footprint
    odom_topic: /odom
    transform_tolerance: 0.3
    bt_loop_duration: 10
    default_server_timeout: 1000 # 1 sec
    wait_for_service_timeout: 1000
    compute_path_error_code: compute_path_error_code
    follow_path_error_code: follow_path_error_code
    
    navigators: ["navigate_to_pose"]
    navigate_to_pose:
      plugin: nav2_bt_navigator::NavigateToPoseNavigator

    # Default behavior trees
    # default_nav_through_poses_bt_xml: ""
    default_nav_to_pose_bt_xml: "/media/mikelap/DATA21/Development/GithubRepos/robotics-sim-projects/uav_project_ws/src/uav_navigation/bt/bt_navigation_w_recalc.xml"
    
    # Plugin library names
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node    # Core navigation actions: planner
    - nav2_follow_path_action_bt_node             # Core navigation actions: controller
    # - nav2_rate_controller_bt_node                # Tree control: pacing
    - nav2_pipeline_sequence_bt_node              # Tree control: sequencing
    # - nav2_clear_costmap_service_bt_node          # Recovery behaviors: clear costmap
    # - nav2_spin_action_bt_node                    # Recovery behaviors: spin recovery
    # - nav2_wait_action_bt_node                    # Recovery behaviors: wait recovery
    # - nav2_back_up_action_bt_node                 # Recovery behaviors: backup recovery
    # - nav2_is_path_valid_condition_bt_node        # Conditions / checks: path validity check
    # - nav2_goal_reached_condition_bt_node         # Conditions / checks: goal reached check
    # - nav2_distance_controller_bt_node            # Conditions / checks: distance‑based control