<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>uav_navigation</name>
  <version>0.0.0</version>
  <description>
    A*-based local collision avoidance stack for UAVs with ROS 2 and PX4.
    Includes Goal Projector, A* local planner and placeholder nodes for obstacle
    detection and command/state machine.
  </description>

  <maintainer email="mi.tamvak@gmail.com">mikelap</maintainer>
  <license>TODO: License declaration</license>

  <!-- C++ / Python dependencies -->
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>px4_msgs</depend>
  <depend>px4_ros_com</depend>

  <exec_depend>python3-numpy</exec_depend>

  <export>
    <!-- Only ONE build type is allowed -->
    <build_type>ament_cmake</build_type>
  </export>
</package>
