controller_manager:
  ros__parameters:
    update_rate: 200  # Hz
    # use_sim_time: true

    velocity_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - front_prop_cw_joint
      - front_prop_ccw_joint
      - back_prop_cw_joint
      - back_prop_ccw_joint
    interface_name: velocity