# Bridge for the Clock plugin
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# # NOTE: This part has to be commented out, because the joint states have to be published
# # from px4 and not from gazebo. This is necessary, because otherwise the propellers will
# # not work in RViz. 
# # Bridge for the JointState plugin
# - ros_topic_name: "joint_states"
#   gz_topic_name: "joint_states"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS

# Bridge for the TF plugin
- ros_topic_name: "/tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Bridge for the rgb image 
- ros_topic_name: "/camera/rgb/image"
  gz_topic_name: "/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  qos_profile: "SENSOR_DATA"

# Bridge for the depth image
- ros_topic_name: "/camera/depth/image"
  gz_topic_name: "/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  qos_profile: "SENSOR_DATA"

# Bridge for camera info
- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  qos_profile: "SENSOR_DATA"

# Bridge for point cloud generated by depth camera
- ros_topic_name: "/camera/cloud"
  gz_topic_name: "/camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  qos_profile: "SENSOR_DATA"
 
# Bridge for 2D LiDAR scan
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  # qos_profile: "SENSOR_DATA"

# Bridge for odometry
- ros_topic_name: "/odom"
  gz_topic_name: "/model/x650_0/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Bridge for IMU
- ros_topic_name: "/imu"
  gz_topic_name: "/world/baylands/model/x650_0/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# # Bridge for GPS navsat
# - ros_topic_name: "gps/fix"
#   ros_type_name: "sensor_msgs/msg/NavSatFix"
#   gz_type_name: "gz.msgs.NavSat"
#   direction: GZ_TO_ROS